### PR TITLE
fix(connection): close connections onModuleDestroy

### PR DESCRIPTION
**Pull request by a-pavlenko**
Currently, module does not close connections after `app.close()` [nestjs lifecycle doc](https://docs.nestjs.com/fundamentals/lifecycle-events), this leads to unexpected behavior when test suite is unable to exit clean and errors like the following:
```
Jest did not exit one second after the test run has completed.
This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

This PR adds onModuleDestroy lifecycle event handler, which closes connection if `keepAlive` option is not specified, hence app can gracefully shutdown.

### CODE REVIEW

**Comment by iamolegga** [comment]
Got the same issue, @skunight can you merge this PR too and publish new version?

**Comment by germansokolov13** [comment]
It should solve my issue https://github.com/kyknow/nestjs-redis/issues/37

**Comment by michaeldever** [comment]
This would be awesome for me as well.

**Comment by lewsmith** [comment]
Can we get this published? 

Pleeeease :+1:

**Pull request merged**
